# This is a basic workflow to help you get started with Actions

name: Global Tests

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      boolean:
        type: boolean
        description: True or False
      deploymentType:
        type: choice
        description: Make a choice
        options:
          - nsg
          - all
      choice1:
        type: choice
        description: Make another choice
        options:
          - he
          - ha
     
env:
  agentWin: windows-latest
  TES: TEST
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment: Dev
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Deploy nsgs
        uses: Azure/powershell@v1
        with:
          # Specify the Az PowerShell script here.
          inlineScript: |
            ./Scripts/New-DeploymentV2.ps1 -templateFile './Modules/Network/nsg.deploy.json' -templateParametersFile @("./Configuration/platform/nprd-prv/nsg/nsg1.parameters.json") -resourceGroupName 'jay-test-rg' -subscriptionId '${{ secrets.AZURE_SUBID }}' ` 
              -buildInfo '${{ github.SHA }} ${{ github.REF_NAME }}'
          azPSVersion: latest
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: jayartifact
          path: ./
     
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo ${{ github.event.inputs.deploymentType }}
          echo ${{ github.event.inputs.choice1 }}
          
  Test:
    needs: build
    if: ${{ success() && github.REF_NAME == 'main' }}
    runs-on: windows-latest
    environment: Dev
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: jayartifact
          
      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_SP }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
          
      - name: Deploy nsgs
        uses: Azure/powershell@v1
        with:
          # Specify the Az PowerShell script here.
          inlineScript: |
            ./Scripts/New-DeploymentV2.ps1 `   
              -templateFile ./Modules/Network/nsg.deploy.json -templateParametersFile @("./Configuration/platform/nprd-prv/nsg/nsg1.parameters.json") -resourceGroupName jay-test-rg -subscriptionId ${{ secrets.AZURE_SUBID }} -buildInfo 'sha main'

          azPSVersion: latest
          
