# This is a basic workflow to help you get started with Actions

name: Global Tests

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
          - foo
          - bar
          - baz
      choice1:
        type: choice
        description: Make another choice
        options:
          - he
          - ha
     
env:
  agentWin: windows-latest
  TES: TEST
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: jayartifact
          path: ./

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "${{ github.event.inputs.choice }}"
          echo ${{ github.event.inputs.choice1 }}
          echo ${{ env.agentWin }}
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}
          dir
          echo ${{ secrets.MY_${{TES}} }}
          
  Test:
    needs: build
    if: failure()
    runs-on: windows-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: jayartifact
          
      - name: Run a one-line script
        run:
          cd ${{ github.workspace }}
