name: reusable

on:
  workflow_call:
    inputs:
      publish_artifacts:
        required: true
        type: string
  pull_request:
    branches:
      - main

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from repo
      - name: cmd
        if: $${{ ${{ github.event.inputs.publish_artifacts && github.event.inputs.publish_artifacts == 'yes' }} }}
        run: echo hahahaha
