name: reusable

on:
  workflow_call:
    inputs:
      publishArtifacts:
        required: true
        type: string
  pull_request:
    branches:
      - main

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from repo
      - name: cmd
        run: |
          echo ${{ github.event.inputs.publishArtifacts }}
          echo ${{ inputs.publishArtifacts }}
      - name: cmd2
        if: ${{ inputs.publishArtifacts && inputs.publishArtifacts == 'yes' }}
        run: |
          echo hahahaha
          echo ${{ github.event.inputs.publish_artifacts }}
