
# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      boolean:
        type: boolean
        description: True or False
      deploymentType:
        type: choice
        description: Make a choice
        options:
          - nsg
          - all
      choice1:
        type: choice
        description: Make another choice
        options:
          - MY_TEST
          - TEST2
      stringInput:
        description: input value
    
    
env:
  testInput: "secrets.${{github.event.inputs.choice1}}"
  envtestInput: "ipos-${{github.event.inputs.stringInput}}"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - run:   |
          write-host ${{env.testInput}}
          write-host ${{secrets.MY_TEST}}
          write-host ${{env.envtestInput}}

            


          
