
# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      boolean:
        type: boolean
        description: True or False
      deploymentType:
        type: choice
        description: Make a choice
        options:
          - nsg
          - all
      choice1:
        type: choice
        description: Make another choice
        options:
          - he
          - ha
     
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: jest-junit
          

            


          
